#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
CONFIG=${CONFIG:-$ROOT/config.env}
COMMAND=help
ARGS=()
while (($#)); do case "$1" in --config) CONFIG=${2:?missing config}; shift 2;; -h|--help) COMMAND=help; shift;; *) COMMAND=$1; shift; ARGS+=("$@"); break;; esac; done
[[ -r "$CONFIG" ]] && source "$CONFIG"
: "${NAMESPACE:=cbt-demo}"; : "${VM_COUNT:=1}"; : "${VM_PREFIX:=fedora-cbt}"; : "${VM_LABEL_SELECTOR:=app.kubernetes.io/name=odf-cbt-validator}"
: "${CONTAINER_IMAGE:=quay.io/containerdisks/fedora:41}"; : "${VM_CPU:=1}"; : "${VM_MEMORY:=1Gi}"; : "${DATA_SIZE:=10Gi}"; : "${BACKUP_SIZE:=20Gi}"
: "${DATA_STORAGE_CLASS:=ocs-storagecluster-ceph-rbd}"; : "${BACKUP_STORAGE_CLASS:=$DATA_STORAGE_CLASS}"; : "${TARGET_NODE:=}"
: "${SSH_KEY:=}"; : "${SSH_PUBLIC_KEY:=}"; : "${SSH_USER:=fedora}"; : "${TIMEOUT:=600}"; : "${STABILIZE_TIMEOUT:=300}"; : "${BACKUP_CONCURRENCY:=2}"; : "${CBT_CHANGE_WAIT:=5}"; : "${REPORTS_DIR:=reports}"
export KUBECONFIG=${KUBECONFIG:-}
if [[ -z $SSH_PUBLIC_KEY && -n $SSH_KEY && -r $SSH_KEY.pub ]]; then SSH_PUBLIC_KEY=$(<"$SSH_KEY.pub"); fi

usage() { cat <<'EOF'
Usage: odf-vm-validator.sh [--config FILE] COMMAND [options]
Commands: generate-keys check-prereqs density-setup density-status density-teardown discover-vms backup cbt-backup verify status ssh report list-reports e2e
Selection options: --vms CSV | --count N | --selector key=value | --all
EOF
}
need() { command -v "$1" >/dev/null || { echo "ERROR: $1 is required" >&2; return 127; }; }
run_id=''; run_dir=''; selected=(); passed=0; failed=0
start_report() { local cmd=$1; run_id="run-$(date -u +%Y%m%dT%H%M%SZ)-$cmd"; run_dir="$REPORTS_DIR/$run_id"; mkdir -p "$run_dir/per-vm"; : >"$run_dir/run.log"; exec > >(tee -a "$run_dir/run.log") 2>&1; started=$(date -u +%Y-%m-%dT%H:%M:%SZ); }
finish_report() { local status=$1; completed=$(date -u +%Y-%m-%dT%H:%M:%SZ); jq -n --arg id "$run_id" --arg c "$COMMAND" --arg ns "$NAMESPACE" --arg s "$started" --arg e "$completed" --argjson sel "$(printf '%s\n' "${selected[@]}" | jq -Rsc 'split("\n")|map(select(length>0))')" --argjson p "$passed" --argjson f "$failed" --argjson r "$(jq -s '.' "$run_dir/per-vm"/*.json 2>/dev/null || echo '[]')" '{runId:$id,command:$c,namespace:$ns,startedAt:$s,completedAt:$e,selected:$sel,passed:$p,failed:$f,results:$r}' >"$run_dir/summary.json"; echo "Report: $run_dir/summary.json"; return "$status"; }
parse_selection() { local mode='' value='' x; while (($#)); do case "$1" in --vms|--count|--selector) [[ -z $mode ]] || { echo 'ERROR: specify exactly one of VMS, N, SELECTOR, or ALL=1' >&2; return 2; }; mode=${1#--}; value=${2-}; shift 2;; --all) [[ -z $mode ]] || { echo 'ERROR: specify exactly one of VMS, N, SELECTOR, or ALL=1' >&2; return 2; }; mode=all; shift;; *) echo "ERROR: unknown option $1" >&2; return 2;; esac; done; [[ -n $mode ]] || { echo 'ERROR: specify exactly one of VMS, N, SELECTOR, or ALL=1' >&2; return 2; }; if [[ $mode == all ]]; then mapfile -t selected < <("$ROOT/scripts/select-vms.sh" --kubeconfig "$KUBECONFIG" --namespace "$NAMESPACE" --base-selector "$VM_LABEL_SELECTOR" --all); else mapfile -t selected < <("$ROOT/scripts/select-vms.sh" --kubeconfig "$KUBECONFIG" --namespace "$NAMESPACE" --base-selector "$VM_LABEL_SELECTOR" "--$mode" "$value"); fi; ((${#selected[@]})) || { echo 'ERROR: selection matched no managed VMs' >&2; return 1; }; }
record() { local vm=$1 status=$2 message=$3; jq -n --arg vm "$vm" --arg st "$status" --arg msg "$message" '{vm:$vm,status:$st,message:$msg}' >"$run_dir/per-vm/$vm.json"; if [[ $status == PASS ]]; then ((passed+=1)); else ((failed+=1)); fi; }
check_prereqs() { for t in oc virtctl kube-burner jq; do need "$t" || return; done; [[ -r ${KUBECONFIG:-/dev/null} || -z ${KUBECONFIG:-} ]] || { echo "ERROR: kubeconfig is unreadable: $KUBECONFIG"; return 1; }; oc get crd virtualmachines.kubevirt.io virtualmachinebackups.backup.kubevirt.io virtualmachinebackuptrackers.backup.kubevirt.io >/dev/null; oc get storageclass "$DATA_STORAGE_CLASS" "$BACKUP_STORAGE_CLASS" >/dev/null; oc get storagecluster,cephcluster -n openshift-storage >/dev/null; oc get volumesnapshotclass -o json | jq -e '.items|length>0' >/dev/null; oc get hyperconverged -A -o json | jq -e '..|objects|select(has("changedBlockTracking"))' >/dev/null; [[ -n $SSH_KEY && -r $SSH_KEY && -r "$SSH_KEY.pub" ]] || echo 'WARNING: SSH_KEY pair not configured; guest checks will fail'; echo 'Prerequisites OK'; }
generate_keys() { [[ -n $SSH_KEY ]] || SSH_KEY="$ROOT/keys/cbt-validator"; mkdir -p "$(dirname "$SSH_KEY")"; if [[ ! -r $SSH_KEY ]]; then ssh-keygen -q -t ed25519 -N '' -f "$SSH_KEY"; fi; SSH_PUBLIC_KEY=$(<"$SSH_KEY.pub"); echo "SSH key: $SSH_KEY"; }
render_job() { local out=$1; sed -e "s|REPLACE_NAMESPACE|$NAMESPACE|g" -e "s|REPLACE_REPLICAS|$VM_COUNT|g" -e "s|REPLACE_VM_PREFIX|$VM_PREFIX|g" -e "s|REPLACE_CONTAINER_IMAGE|$CONTAINER_IMAGE|g" -e "s|REPLACE_SSH_USER|$SSH_USER|g" -e "s|REPLACE_SSH_PUBLIC_KEY|$SSH_PUBLIC_KEY|g" -e "s|REPLACE_VM_CPU|$VM_CPU|g" -e "s|REPLACE_VM_MEMORY|$VM_MEMORY|g" -e "s|REPLACE_DATA_SIZE|$DATA_SIZE|g" -e "s|REPLACE_BACKUP_SIZE|$BACKUP_SIZE|g" -e "s|REPLACE_DATA_STORAGE_CLASS|$DATA_STORAGE_CLASS|g" -e "s|REPLACE_BACKUP_STORAGE_CLASS|$BACKUP_STORAGE_CLASS|g" -e "s|REPLACE_TARGET_NODE|$TARGET_NODE|g" "$ROOT/kube-burner/odf-cbt-density.yml" >"$out"; }
density_setup() { [[ $VM_COUNT =~ ^[1-9][0-9]*$ ]] || { echo 'ERROR: VM_COUNT must be positive'; return 2; }; local existing; existing=$(oc get namespace "$NAMESPACE" -o jsonpath='{.metadata.labels.app\.kubernetes\.io/managed-by}' 2>/dev/null || true); if oc get namespace "$NAMESPACE" >/dev/null 2>&1; then [[ $existing == odf-cbt-validator ]] || { echo "ERROR: namespace $NAMESPACE is not utility-owned"; return 1; }; else oc create namespace "$NAMESPACE"; oc label namespace "$NAMESPACE" app.kubernetes.io/managed-by=odf-cbt-validator --overwrite; fi; if oc get vm -n "$NAMESPACE" -l "$VM_LABEL_SELECTOR" -o name | grep -q .; then echo 'ERROR: managed VM pool already exists; teardown first' >&2; return 1; fi; local job; mkdir -p "$ROOT/kube-burner/rendered"; job=$(mktemp "$ROOT/kube-burner/rendered/density.XXXX.yml"); render_job "$job"; (cd "$ROOT/kube-burner" && kube-burner init --config "rendered/$(basename "$job")" --kubeconfig "$KUBECONFIG" --log-level error); rm -f "$job"; wait_pool; }
wait_pool() { local deadline=$((SECONDS+STABILIZE_TIMEOUT)); while ((SECONDS<deadline)); do local count ready; count=$(oc get vm -n "$NAMESPACE" -l "$VM_LABEL_SELECTOR" --no-headers 2>/dev/null | wc -l | tr -d ' '); ready=$(oc get vm -n "$NAMESPACE" -l "$VM_LABEL_SELECTOR" -o json | jq '[.items[]|select(.status.ready==true and .status.changedBlockTracking.state=="Enabled")]|length'); if [[ $count == "$VM_COUNT" && $ready == "$VM_COUNT" ]]; then break; fi; sleep 5; done; mapfile -t selected < <("$ROOT/scripts/select-vms.sh" --kubeconfig "$KUBECONFIG" --namespace "$NAMESPACE" --base-selector "$VM_LABEL_SELECTOR" --count "$VM_COUNT"); ((${#selected[@]} == VM_COUNT)) || { echo 'ERROR: VM pool did not become ready'; return 1; }; for vm in "${selected[@]}"; do oc wait --for=jsonpath='{.status.ready}'=true vm/"$vm" -n "$NAMESPACE" --timeout="${TIMEOUT}s"; oc wait --for=jsonpath='{.status.phase}'=Running vmi/"$vm" -n "$NAMESPACE" --timeout="${TIMEOUT}s"; done; }
density_status() { if [[ ${COUNT_ONLY:-} == 1 ]]; then oc get vm -n "$NAMESPACE" -l "$VM_LABEL_SELECTOR" --no-headers | wc -l; elif [[ ${SUMMARY:-} == 1 ]]; then oc get vm -n "$NAMESPACE" -l "$VM_LABEL_SELECTOR" -o json | jq '{count:(.items|length),ready:([.items[]|select(.status.ready==true)]|length),cbtEnabled:([.items[]|select(.status.changedBlockTracking.state=="Enabled")]|length)}'; else oc get vm,vmi,pvc,virtualmachinebackuptracker -n "$NAMESPACE" -l "$VM_LABEL_SELECTOR" -o wide; fi; }
density_teardown() { local owned; owned=$(oc get namespace "$NAMESPACE" -o jsonpath='{.metadata.labels.app\.kubernetes\.io/managed-by}' 2>/dev/null || true); [[ $owned == odf-cbt-validator ]] || { echo "ERROR: refusing unowned namespace $NAMESPACE" >&2; return 1; }; oc delete namespace "$NAMESPACE" --wait=true; }
discover() { if (($#==0)); then set -- --all; fi; parse_selection "$@"; if [[ ${COUNT_ONLY:-} == 1 ]]; then printf '%s\n' "${#selected[@]}"; else printf '%s\n' "${selected[@]}"; fi; }
wait_backup() { local vm=$1 name=$2; oc wait --for=jsonpath='{.status.conditions[?(@.type=="Done")].status}'=True virtualmachinebackup/"$name" -n "$NAMESPACE" --timeout="${TIMEOUT}s" 2>/dev/null || oc wait --for=jsonpath='{.status.conditions[?(@.type=="Complete")].status}'=True virtualmachinebackup/"$name" -n "$NAMESPACE" --timeout="${TIMEOUT}s"; local typ; typ=$(oc get virtualmachinebackup "$name" -n "$NAMESPACE" -o json | jq -r '.status.type // empty'); [[ $typ == "$3" ]] || { echo "backup $name for $vm has type $typ, expected $3"; return 1; }; }
backup_one() { local vm=$1 name=$2 tracker="$vm-tracker" pvc="$vm-backup-output"; local checkpoint; checkpoint=$(oc get virtualmachinebackuptracker "$tracker" -n "$NAMESPACE" -o json | jq -r '.status.latestCheckpoint // .status.checkpointName // empty'); [[ -z $checkpoint ]] || { echo "full backup already exists for $vm; use cbt-backup or recreate density"; return 1; }; oc delete virtualmachinebackup "$name" -n "$NAMESPACE" --ignore-not-found; cat <<EOF | oc apply -f -
apiVersion: backup.kubevirt.io/v1alpha1
kind: VirtualMachineBackup
metadata: {name: $name, namespace: $NAMESPACE}
spec:
  source: {apiGroup: backup.kubevirt.io, kind: VirtualMachineBackupTracker, name: $tracker}
  mode: Push
  pvcName: $pvc
  skipQuiesce: true
EOF
wait_backup "$vm" "$name" Full; }
cbt_one() { local vm=$1 name=$2 tracker="$vm-tracker" pvc="$vm-backup-output"; oc get virtualmachinebackup "$vm-full" -n "$NAMESPACE" >/dev/null; local before; before=$(oc get virtualmachinebackuptracker "$tracker" -n "$NAMESPACE" -o json | jq -r '.status.latestCheckpoint // .status.checkpointName // empty'); [[ -n $before ]] || { echo "no full checkpoint for $vm"; return 1; }; oc delete virtualmachinebackup "$name" -n "$NAMESPACE" --ignore-not-found; cat <<EOF | oc apply -f -
apiVersion: backup.kubevirt.io/v1alpha1
kind: VirtualMachineBackup
metadata: {name: $name, namespace: $NAMESPACE}
spec:
  source: {apiGroup: backup.kubevirt.io, kind: VirtualMachineBackupTracker, name: $tracker}
  mode: Push
  pvcName: $pvc
  skipQuiesce: true
EOF
wait_backup "$vm" "$name" Incremental; local after; after=$(oc get virtualmachinebackuptracker "$tracker" -n "$NAMESPACE" -o json | jq -r '.status.latestCheckpoint // .status.checkpointName // empty'); [[ -n $after && $after != "$before" ]] || { echo "tracker did not advance for $vm"; return 1; }; }
run_selected() { local action=$1; shift; parse_selection "$@"; start_report "$action"; local vm; for vm in "${selected[@]}"; do if [[ $action == backup ]]; then backup_one "$vm" "$vm-full" && record "$vm" PASS 'Full backup completed' || record "$vm" FAIL 'Full backup failed'; elif [[ $action == cbt-backup ]]; then sleep "$CBT_CHANGE_WAIT"; cbt_one "$vm" "$vm-incremental" && record "$vm" PASS 'Incremental backup completed' || record "$vm" FAIL 'Incremental backup failed'; else verify_one "$vm" && record "$vm" PASS 'VM, backup and guest checks passed' || record "$vm" FAIL 'Verification failed'; fi; done; ((failed==0)) && finish_report 0 || finish_report 1; }
guest_check() { local vm=$1 output; [[ -n $SSH_KEY ]] || return 1; output=$(virtctl ssh -n "$NAMESPACE" -i "$SSH_KEY" --known-hosts=/dev/null --local-ssh-opts='-o' --local-ssh-opts='StrictHostKeyChecking=no' "$SSH_USER@vm/$vm" --command "test -f /data/vm-validator/workload.db -a -f /data/vm-validator/workload.log; mountpoint -q /data; sqlite3 /data/vm-validator/workload.db 'pragma integrity_check' | grep -qx ok; python3 -c \"import sqlite3,hashlib; c=sqlite3.connect('/data/vm-validator/workload.db'); r=c.execute('select seq,payload,digest from records order by seq').fetchall(); assert r and [x[0] for x in r]==list(range(1,len(r)+1)); assert all(hashlib.sha256(x[1].encode()).hexdigest()==x[2] for x in r)\"; echo GUEST_CHECK_OK"); grep -qx GUEST_CHECK_OK <<<"$output"; }
verify_one() { local vm=$1; oc wait --for=jsonpath='{.status.ready}'=true vm/"$vm" -n "$NAMESPACE" --timeout="${TIMEOUT}s"; oc wait --for=jsonpath='{.status.phase}'=Running vmi/"$vm" -n "$NAMESPACE" --timeout="${TIMEOUT}s"; oc get vm "$vm" -n "$NAMESPACE" -o json | jq -e '.status.changedBlockTracking.state=="Enabled"' >/dev/null; oc get pvc "$vm-data" "$vm-backup-output" -n "$NAMESPACE" -o json | jq -e '[.items[].status.phase]|all(.=="Bound")' >/dev/null; wait_backup "$vm" "$vm-full" Full; wait_backup "$vm" "$vm-incremental" Incremental; guest_check "$vm"; sleep 2; guest_check "$vm"; }
status_selected() { if (($#==0)); then set -- --all; fi; parse_selection "$@"; printf '%-32s %-8s %-10s %-12s %-12s %-12s %s\n' VM READY PHASE CBT FULL INCREMENTAL CHECKPOINT; local vm full inc cp; for vm in "${selected[@]}"; do full=$(oc get virtualmachinebackup "$vm-full" -n "$NAMESPACE" -o json 2>/dev/null | jq -r '.status.type // .status.conditions[0].reason // -'); inc=$(oc get virtualmachinebackup "$vm-incremental" -n "$NAMESPACE" -o json 2>/dev/null | jq -r '.status.type // .status.conditions[0].reason // -'); cp=$(oc get virtualmachinebackuptracker "$vm-tracker" -n "$NAMESPACE" -o json 2>/dev/null | jq -r '.status.latestCheckpoint // .status.checkpointName // -'); printf '%-32s %-8s %-10s %-12s %-12s %-12s %s\n' "$vm" "$(oc get vm "$vm" -n "$NAMESPACE" -o jsonpath='{.status.ready}' 2>/dev/null || echo -)" "$(oc get vmi "$vm" -n "$NAMESPACE" -o jsonpath='{.status.phase}' 2>/dev/null || echo -)" "$(oc get vm "$vm" -n "$NAMESPACE" -o jsonpath='{.status.changedBlockTracking.state}' 2>/dev/null || echo -)" "$full" "$inc" "$cp"; done; }
ssh_guest() { local vm='' cmd=''; while (($#)); do case "$1" in --vm) vm=${2-}; shift 2;; --cmd) cmd=${2-}; shift 2;; *) return 2;; esac; done; [[ -n $vm && $vm == "$VM_PREFIX"-* ]] || { echo 'ERROR: VM is required and must use configured prefix' >&2; return 2; }; [[ -n $SSH_KEY ]] || { echo 'ERROR: SSH_KEY is required' >&2; return 2; }; virtctl ssh -n "$NAMESPACE" -i "$SSH_KEY" --known-hosts=/dev/null --local-ssh-opts='-o StrictHostKeyChecking=no' "$SSH_USER@vm/$vm" --command "${cmd:-hostname}"; }
report() { local f; f=$(find "$REPORTS_DIR" -name summary.json -print | sort | sed -n '$p'); [[ -n $f ]] && cat "$f" || { echo 'No reports'; return 1; }; }
list_reports() { find "$REPORTS_DIR" -mindepth 1 -maxdepth 1 -type d -print 2>/dev/null | sort -r; }
e2e() { local count=${1:-$VM_COUNT}; density_setup; local sel=(--count "$count"); run_selected backup "${sel[@]}"; run_selected cbt-backup "${sel[@]}"; run_selected verify "${sel[@]}"; report; }
case "$COMMAND" in
 help) usage;; generate-keys) generate_keys;; check-prereqs) check_prereqs;; density-setup) [[ ${ARGS[0]:-} == --count ]] && VM_COUNT=${ARGS[1]}; density_setup;; density-status) density_status;; density-teardown) density_teardown;; discover-vms) discover "${ARGS[@]}";; backup|cbt-backup|verify) run_selected "$COMMAND" "${ARGS[@]}";; status) status_selected "${ARGS[@]}";; ssh) ssh_guest "${ARGS[@]}";; report) report;; list-reports) list_reports;; e2e) [[ ${ARGS[0]:-} == --count ]] && VM_COUNT=${ARGS[1]}; e2e "$VM_COUNT";; *) usage >&2; exit 2;; esac
